### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by williamhallatt**
Added a problem viewer/demo app.

### CODE REVIEW

**Comment by pdrozdowski** [comment]
I wouldn't like to add ui to this project, sorry.

**Comment by williamhallatt** [comment]
Hi Pawel,

Not sure if you noticed that it is a completely different solution (not
added to the lib .sln)? But cool :)

On 31 July 2015 at 20:33, Pawel Drozdowski notifications@github.com wrote:

> I wouldn't like to add ui to this project, sorry.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pdrozdowski/TSPLib.Net/pull/5#issuecomment-126778181.

## 

_"They say a little knowledge is a dangerous thing, but it's not one half
so bad as a lot of ignorance." - Terry Pratchett_

**Comment by pdrozdowski** [comment]
Noticed, It might be good idea to make tsplib/net a nuget package to which you can reference the viewer as a separate project if you would like. But i would like to keep library minimized so to have only things that are required, so you cannot remove anything and still have it working. UI App is against that.

**Comment by williamhallatt** [comment]
OK cool.

On 1 August 2015 at 08:44, Pawel Drozdowski notifications@github.com
wrote:

> Noticed, It might be good idea to make tsplib/net a nuget package to which
> you can reference the viewer as a separate project if you would like. But i
> would like to keep library minimized so to have only things that are
> required, so you cannot remove anything and still have it working. UI App
> is against that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pdrozdowski/TSPLib.Net/pull/5#issuecomment-126874868.

## 

_"They say a little knowledge is a dangerous thing, but it's not one half
so bad as a lot of ignorance." - Terry Pratchett_

**Pull request closed without merging**
